services:
  influxdb:
    image: influxdb:1.11
    container_name: influxdb
    user: "0"
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Etc/UTC}
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpassword
    volumes:
      - ./volumes/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ./volumes/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    network_mode: host

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Etc/UTC}
    user: "0"
    volumes:
      - ./volumes/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ./volumes/mosquitto/config:/mosquitto/config
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"

  portainer-ce:
    image: portainer/portainer-ce:latest
    container_name: portainer-ce
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer:/data
    ports:
      - "9000:9000"

  tasmoadmin:
    image: raymondmm/tasmoadmin:latest
    container_name: tasmoadmin
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Etc/UTC}
    ports:
      - "8088:80"
    volumes:
      - ./volumes/tasmoadmin/data:/data

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: "host"
    environment:
      TZ: ${TZ:-Etc/UTC}
      FTLCONF_webserver_api_password: wt9mwt9m
      FTLCONF_dns_upstreams: 1.1.1.1;9.9.9.9
      FTLCONF_database_maxDBdays: 91
    volumes:
      - ./volumes/pihole6/etc-pihole:/etc/pihole
      - ./volumes/pihole6/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN


  can2mqtt_hawkesbay:
    container_name: can2mqtt_hawkesbay
    build: ./services/can2mqtt_hawkesbay
    restart: unless-stopped
    network_mode: "host"
    environment:
      - MQTT_BROKER=127.0.0.1
      - MQTT_PORT=1883
      - MQTT_PREFIX=hawkesbay
      - CAN_INTERFACE=can0
