
networks:
  default:
    driver: bridge
    ipam:
      driver: default
  nextcloud:
    driver: bridge
    internal: true
    ipam:
      driver: default

services:
  mosquitto:
    container_name: mosquitto
    build:
      context: ./.templates/mosquitto/.
      args:
      - MOSQUITTO_BASE=eclipse-mosquitto:latest
    restart: unless-stopped
    environment:
    - TZ=${TZ:-Etc/UTC}
    ports:
    - "1883:1883"
    volumes:
    - ./volumes/mosquitto/config:/mosquitto/config
    - ./volumes/mosquitto/data:/mosquitto/data
    - ./volumes/mosquitto/log:/mosquitto/log
    - ./volumes/mosquitto/pwfile:/mosquitto/pwfile

  influxdb:
    container_name: influxdb
    image: "influxdb:1.11"
    restart: unless-stopped
    user: "0"
    ports:
    - "8086:8086"
    environment:
    - TZ=Etc/UTC
    - INFLUXDB_HTTP_FLUX_ENABLED=false
    - INFLUXDB_REPORTING_DISABLED=false
    - INFLUXDB_HTTP_AUTH_ENABLED=false
    - INFLUXDB_MONITOR_STORE_ENABLED=FALSE
  # - INFLUX_USERNAME=<your username>
  # - INFLUX_PASSWORD=<your password>
  # - INFLUXDB_UDP_ENABLED=false
  # - INFLUXDB_UDP_BIND_ADDRESS=0.0.0.0:8086
  # - INFLUXDB_UDP_DATABASE=udp
    volumes:
    - ./volumes/influxdb/data:/var/lib/influxdb
    - ./backups/influxdb/db:/var/lib/influxdb/backup
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8086"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    user: "0"
    ports:
    - "3000:3000"
    environment:
    - TZ=Etc/UTC
    - GF_PATHS_DATA=/var/lib/grafana
    - GF_PATHS_LOGS=/var/log/grafana
    volumes:
    - ./volumes/grafana/data:/var/lib/grafana
    - ./volumes/grafana/log:/var/log/grafana
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  portainer-ce:
    container_name: portainer-ce
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
    - "8000:8000"
    - "9000:9000"
    # HTTPS
    - "9443:9443"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./volumes/portainer-ce/data:/data

  tasmoadmin:
    container_name: tasmoadmin
    image: ghcr.io/tasmoadmin/tasmoadmin:latest
    restart: unless-stopped
    environment:
    - TZ=Etc/UTC
    ports:
    - "8088:80"
    volumes:
    - ./volumes/tasmoadmin/data:/data

  telegraf:
    container_name: telegraf
    build: ./.templates/telegraf/.
    hostname: iotstack # optional
    restart: unless-stopped
    environment:
    - TZ=${TZ:-Etc/UTC}
    ports:
    - "8092:8092/udp"
    - "8094:8094/tcp"
    - "8125:8125/udp"
    volumes:
    - ./volumes/telegraf:/etc/telegraf
    - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
    - influxdb
    - mosquitto

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: "host"
    environment:
      TZ: ${TZ:-Etc/UTC}
      FTLCONF_webserver_api_password:<your password>
      FTLCONF_dns_upstreams: 1.1.1.1;9.9.9.9
      FTLCONF_database_maxDBdays: 91
    volumes:
      - ./volumes/pihole6/etc-pihole:/etc/pihole
      - ./volumes/pihole6/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN


  can2mqtt_hawkesbay:
    container_name: can2mqtt_hawkesbay
    build: ./services/can2mqtt_hawkesbay
    restart: unless-stopped
    network_mode: "host"
    environment:
      - MQTT_BROKER=<your ip>
      - MQTT_PORT=1883
      - MQTT_PREFIX=hawkesbay
      - CAN_INTERFACE=can0

