version: '3'

services:
  can2mqtt_hawkesbay:
    container_name: can2mqtt_hawkesbay
    build: ./services/can2mqtt_hawkesbay
    restart: unless-stopped
    network_mode: "host"
    environment:
      - MQTT_BROKER=127.0.0.1
      - MQTT_PORT=1883
      - MQTT_PREFIX=hawkesbay
      - CAN_INTERFACE=can0
